server:
  port: 8002

# ==========applicationName + druid-mysql8 driver===================
spring:
  jackson:  #统一时间格式返回
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud2024?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: root

# ========================mybatis===================
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.cloud.entities
  configuration:
    map-underscore-to-camel-case: true